#!/usr/bin/env python3
"""Emit a SYNTHETIC, non-functional service account for local test collection.

``email_automation/clients.py`` constructs ``firestore.Client()`` at IMPORT time
(backlog #84), so merely importing the product needs a credential file to exist.
Every certification run therefore depends on one.

That credential used to be generated by hand into a session scratchpad under
``/tmp``. The scratchpad was garbage-collected, and with it went the credential
AND the regression-sweep baselines - so the instruments the build called
mandatory simply stopped existing. A generator checked into the repo cannot
evaporate; the credential it emits still never enters the repo.

The key below is a freshly generated RSA key with no counterpart anywhere. The
project id and client email are ``.invalid`` (RFC 2606). It authenticates to
nothing.

    python3 scripts/make_synthetic_credential.py /path/outside/the/repo/sa.json

NEVER point GOOGLE_APPLICATION_CREDENTIALS at a real service account when
running certification. A real credential lets the import-time client reach
production.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def build(private_key_pem: str) -> dict:
    return {
        "type": "service_account",
        "project_id": "synthetic-certification-invalid",
        "private_key_id": "0" * 40,
        "private_key": private_key_pem,
        "client_email": "synthetic@synthetic-certification-invalid.iam.gserviceaccount.invalid",
        "client_id": "000000000000000000000",
        "auth_uri": "https://accounts.google.invalid/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.invalid/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.invalid/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.invalid/robot/v1/metadata/x509/synthetic",
        "universe_domain": "googleapis.invalid",
    }


def generate_key() -> str:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    return key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode("ascii")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("destination", type=Path)
    args = parser.parse_args(argv)

    destination = args.destination.resolve()
    # A credential inside the checkout is how one ends up somewhere nobody tracks.
    if REPO_ROOT in destination.parents or destination.parent == REPO_ROOT:
        print(f"refusing to write a credential inside the repo: {destination}",
              file=sys.stderr)
        return 2

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(build(generate_key()), indent=2) + "\n")
    os.chmod(destination, 0o600)
    print(destination)
    return 0


if __name__ == "__main__":
    sys.exit(main())
