name: Email Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install msal requests openpyxl

      - name: Restore MSAL cache
        run: echo "${{ secrets.MSAL_CACHE_B64 }}" | base64 --decode > msal_token_cache.bin

      - name: Run email script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: python noPopup_signin_emails_to_excel.py
