name: Email Automation
on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Every 5 minutes (for testing)

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install msal requests openpyxl firebase-admin
          
      - name: Run email script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_API_APP_ID: ${{ secrets.AZURE_API_APP_ID }}
          AZURE_API_CLIENT_SECRET: ${{ secrets.AZURE_API_CLIENT_SECRET }}
        # run: python noPopup_signin_emails_to_excel.py
        run: python main.py
